### ISSUE TITLE
Ghost blocks

### ISSUE THREAD

**Issue by Knito58** [DuelMonster/MinersAdvantage#2]
After cutting away some lines of dirt / sand / stone with the shaftinator there are some leftovers: invisible ghost blocks. I can jump on top of them and stand in the air. When standing in the air on such a block, there's a "wobble effect". It seems as if the local world wants me to fall through while the server puts me back up on the block again. Moving away is nearly not possible.

Maybe a problem with falling blocks?

But all in all: This rework is a great success! 

Versions:

MA 1.3.14.189
Forge 14.23.2.2654
MC 1.12.2
Survival Single Player

Edit: After re-joining the world my avatar is on top of a sand block. Leaving the world for a moment fixes this one atm.

**Comment by Thrombor2017** [comment]
Hello, i was about to report this issue too, this is indeed due to falling blocks, it happens everytime using shaftanator/excavator and blocks like sand or gravel are present. if you place any block where the gravel/sand was, the block you just placed will be transformed into the sand/gravel; So when it happens i some blocks in the "bugged area" then use dig in again and its gone.
As knito said, great rework overall, i like it!
PS: sorry for my english

**Comment by DuelMonster** [comment]
I am aware of ghost block issues and I've found that increasing the tick delay or decreasing the blocks per tick can help to solve this.

However it is on my list and I'll look at it soon. Like u say it mainly happens with falling block types.

**Comment by Knito58** [comment]
Thanks @Thrombor2017: I didn't think of that.
As @DuelMonster said my config now processes only 1 block per tick instead of 2.

**Comment by Knito58** [comment]
I have GravelMiner installed. Maybe thats a problem. Superminer did not have a problem with gravelminer. I mention this because sand or gravel blocks right above a shaft do not become "gravelmined". Maybe there's still some block update event missing.

**Comment by DuelMonster** [comment]
@Knito58, It is quite possible that Gravel miner isn't firing due to the way MinersAdvantage is harvesting the blocks. SuperMiner breaks blocks in batches, where as MinersAdvantage does it more on a per block basis.
It may be easier to extend MinerAdvantge to include a similar feature to GravelMiner.  The one thing about GravelMiner I never liked was the way it places a torch to get the job done on a client only world and works differently for a Server.  Client only runs an internal server instance anyway so why not do it the same way...?

**Comment by Knito58** [comment]
Ok. I thought that GM could somehow be the source of ghost blocks as it did not behave as expected. Now it is out of the way. I believe that it is more important to solve the ghost block problem than to mimic gravelminer's behaviour. 

Meanwhile I also found some tree leave blocks which were ghost blocks, too.  Weird.

**Comment by DuelMonster** [comment]
Hmm, that's odd. I've never seen it ghost leaf blocks before...

I'll look into it as soon as I'm able.

**Comment by Knito58** [comment]
Update: 

@DuelMonster:

Ghost Blocks spawn for sure in the Nether and in the End. Mining with MA in the Nether is not possible for me as every Block turns into a ghost block. Mining in the End also. I tried to shaftinate some end blocks and visually a shaft was made. But every removed block had turned into a ghost block and had to be cleared with @Thrombor2017 solution.

**Comment by Knito58** [comment]
Hi @DuelMonster ,

I had this page open but it did not refresh so I didn't see your posting in time. Sorry.

You're right, I have non standard digging tools. I dig with Actually Addition's Obsidian AIOT and Diamond AIOT, both enchanted with fortune and sometimes efficiency. My avatar has "Everlasting Abilities": Haste and some other non digging related powers.

With MA and "Excavation" you can collect very quickly a lot of obsidian with the "ice bucket technic". So in eartly game I go for Obsidian AIOTs, which are compatible with MA when added to the tools list. When my energy system is set up I use "reconstruction" to repair one of my tool and armor sets and make Diamond AIOTs.

I was in the End to collect some End Stones and Rods for an "Ender Quarry" (extrautils2). I know that MA works in non-Overworld worlds but was not aware if this was tool-dependent. Will visit the End again with a diamond pickaxe and an AIOT and see what happens.

**Comment by DuelMonster** [comment]
Thanks for the excellent feedback @Knito58, it's much appreciated!  I'm glad that things are running as expected again.

I did not get around to looking into the issue over the weekend... IRL stuff got in the way.  But I am determined to get on it as soon as possible.

"Haste" is a real issue for MA because of the whole client to server de-sync. I've tried to mimic how MC does all its block harvesting as much as possible, but I guess I'm still missing something.
I've been thinking about the original issue and have a good idea on where to start, so once I get going, it shouldn't be too long before I get an update out.

I've never used the Actually Addition's AIOTs, even though I have it installed and use other aspects of the mod.  I'll keep it in mind and will look to running some further tests with them, just to rule out any issues.  I'll also get them added to the tools lists automatically within my thrid-party compatibility code.

Thanks
DuelMonster

**Comment by Knito58** [comment]
Thanks you for the flowers. Again I was afk for 2 days in RL. Sorry for not answering in time.

Greetings,
Konitor

**Comment by DuelMonster** [comment]
That's not a problem. I know all to well what RL can dish out at times.
Just the fact you use my mod is enough to make me happy 😉

I'm looking into the problem right now...

Cheers
DuelMonster

**Comment by DuelMonster** [comment]
Well @Knito58 I do believe I may have solved the Ghost block issue... I will spend a few days testing just to be sure tho.
I'm also working on a couple of other issues as well that have been bugging me.

**Comment by Knito58** [comment]
Thumbs up! Great!

**Comment by DuelMonster** [comment]
@Knito58 New release has just been uploaded.

It works in much the same way as Gravel Miner.  Would you mind just giving it a go and letting me know that all's good before I close of the issue.

Thanks
DuelMonster

**Comment by DuelMonster** [comment]
That's great news!

Happy to be of service! And thank you for using MA! 🤗
